sass:
    sass_dir: assets/uswds/scss

plugins:
  - jekyll-get-json

jekyll_get_json:
  - data: colors
    json: 'https://v1.nocodeapi.com/pglevy/airtable/PlbDABvSrEKqjPdL?tableName=color'
  - data: components
    json: 'https://v1.nocodeapi.com/pglevy/airtable/LDTzULYnuAgBNkGH?tableName=components'

collections:
  components:
    output: true