title: USWDS Token Playground
description: "An experiment with using Jekyll/GHP to build a USWDS site that pulls tokens into SASS from JSON."

sass:
    sass_dir: assets/uswds/scss

plugins:
  - jekyll-get-json

# for nocodeapi
# jekyll_get_json:
#   - data: colors
#     json: 'https://v1.nocodeapi.com/pglevy/airtable/PlbDABvSrEKqjPdL?tableName=color'
#   - data: components
#     json: 'https://v1.nocodeapi.com/pglevy/airtable/LDTzULYnuAgBNkGH?tableName=components'

collections:
  components:
    output: true

# This is just to force a rebuild on GitHub Pages if it fails for some reason. It seems to fail periodically.
rebuild: 1